import { Header } from "@/components/header"
import { Footer } from "@/components/footer"
import Link from "next/link"

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-background flex flex-col">
      <Header />
      <main className="flex-1 container mx-auto py-12 px-4">
        <div className="max-w-4xl mx-auto">
          <h1 className="text-4xl font-heading font-bold mb-6">Terms of Service</h1>
          <div className="bg-card rounded-xl shadow-md border p-8 prose prose-gray dark:prose-invert max-w-none">
            <p className="text-lg text-muted-foreground mb-6">Last updated: June 2024</p>

            <h2>Acceptance of Terms</h2>
            <p>
              By using Applyfit, you agree to these Terms of Service. If you do not agree, please do not use our service.
            </p>

            <h2>Service Description</h2>
            <p>
              Applyfit is an AI-powered tool for generating resumes and cover letters. The service is provided "as is" without warranty of any kind. We do not guarantee job placement, interview offers, or any employment outcome.
            </p>

            <h2>User Responsibilities</h2>
            <ul>
              <li>Provide accurate and lawful information</li>
              <li>Use the service for legal purposes only</li>
              <li>Do not attempt to reverse engineer, misuse, or disrupt the service</li>
              <li>Respect all intellectual property rights</li>
            </ul>

            <h2>Limitation of Liability</h2>
            <p>
              To the fullest extent permitted by law, Applyfit and its owners, affiliates, and partners are not liable for any direct, indirect, incidental, or consequential damages arising from your use of the service. You use Applyfit at your own risk.
            </p>
            <p>
              Applyfit does not guarantee the accuracy, completeness, or suitability of any content generated by the service. You are solely responsible for reviewing and using any generated materials.
            </p>

            <h2>Indemnification</h2>
            <p>
              You agree to indemnify and hold harmless Applyfit and its affiliates from any claims, damages, or expenses arising from your use of the service or violation of these terms.
            </p>

            <h2>Changes to Terms</h2>
            <p>
              We may update these Terms of Service at any time. Continued use of Applyfit after changes constitutes acceptance of the new terms.
            </p>

            <h2>Contact</h2>
            <p>
              For all legal or support inquiries, please use our <Link href="/support" className="text-primary hover:underline">Contact page</Link>.
            </p>
          </div>
        </div>
      </main>
      <Footer />
    </div>
  )
}
